import type { BusinessMarket } from "@/lib/types";

// Faturalandırma sayfası TR ve US işletmeleri için aynı; yalnızca metin ve
// tarih/para biçimi pazara göre değişir.
const tr = {
  locale: "tr-TR",
  title: "Faturalandırma",
  intro: "Aboneliğin, sonraki fatura tarihin ve kayıtlı ödeme yöntemin.",
  providerLabel: "Ödeme sağlayıcısı",
  provider: { stripe: "Stripe", iyzico: "iyzico", paypal: "PayPal" },
  plan: "Mevcut plan",
  planFallback: "Locally aboneliği",
  status: "Durum",
  statuses: {
    active: "Aktif",
    past_due: "Ödeme bekleniyor",
    canceled: "İptal edildi",
    trialing: "Deneme süresi",
    unpaid: "Ödenmedi",
    incomplete: "Tamamlanmadı",
  } as Record<string, string>,
  endsOn: "Bitiş tarihi",
  nextInvoice: "Sonraki fatura",
  paymentMethod: "Ödeme yöntemi",
  noPaymentMethod: "Kayıtlı kart bilgisi alınamadı",
  paypalAccount: "PayPal hesabı (ödeme yöntemi PayPal'da yönetilir)",
  expires: "son kullanma",
  lastPayment: "Son ödeme",
  perInterval: { day: "gün", week: "hafta", month: "ay", year: "yıl" } as Record<string, string>,
  cancelScheduled: "Aboneliğin {date} tarihinde sona erecek. O güne kadar tüm özellikler açık.",
  cancelScheduledNoDate: "Aboneliğin mevcut dönemin sonunda sona erecek.",
  canceled: "Aboneliğin iptal edildi.",
  pastDue: "Son ödeme alınamadı. Kart bilgin güncellenmezse hizmet duraklatılabilir.",
  noSubscription: "Henüz aktif bir aboneliğin yok.",
  noSubscriptionTr: "Locally Türkiye'de şu an ücretsiz erken erişim döneminde — abonelik gerekmiyor.",
  liveUnavailable: "Ödeme sağlayıcısına şu an ulaşılamadı; ayrıntılar kısa süre sonra görünecek.",
  simulated: "Test modu: ödeme sağlayıcısı yapılandırılmadığı için bilgiler simüle ediliyor.",
  cancel: {
    button: "Aboneliği iptal et",
    question: "Aboneliğin ne zaman sona ersin?",
    periodEndTitle: "Dönem sonunda (önerilen)",
    periodEndBody: "{date} tarihine kadar hizmet devam eder, sonra yenilenmez. Ek ücret alınmaz.",
    periodEndBodyNoDate: "Ödediğin dönemin sonuna kadar hizmet devam eder, sonra yenilenmez.",
    nowTitle: "Hemen",
    nowBody: "Hizmet şimdi durur. Kalan günler için iade yapılmaz.",
    confirm: "İptali onayla",
    pending: "İptal ediliyor…",
    keep: "Vazgeç",
    doneNow: "Aboneliğin iptal edildi.",
    doneAtPeriodEnd: "Aboneliğin dönem sonunda sona erecek şekilde ayarlandı.",
  },
};

export type BillingCopy = typeof tr;

const en: BillingCopy = {
  locale: "en-US",
  title: "Billing",
  intro: "Your subscription, next invoice date and payment method.",
  providerLabel: "Payment provider",
  provider: { stripe: "Stripe", iyzico: "iyzico", paypal: "PayPal" },
  plan: "Current plan",
  planFallback: "Locally subscription",
  status: "Status",
  statuses: {
    active: "Active",
    past_due: "Payment due",
    canceled: "Canceled",
    trialing: "Trial",
    unpaid: "Unpaid",
    incomplete: "Incomplete",
  },
  endsOn: "Ends on",
  nextInvoice: "Next invoice",
  paymentMethod: "Payment method",
  noPaymentMethod: "No card details available",
  paypalAccount: "PayPal account (manage your payment method in PayPal)",
  expires: "expires",
  lastPayment: "Last payment",
  perInterval: { day: "day", week: "week", month: "month", year: "year" },
  cancelScheduled: "Your subscription ends on {date}. Everything keeps working until then.",
  cancelScheduledNoDate: "Your subscription ends at the end of the current billing period.",
  canceled: "Your subscription has been canceled.",
  pastDue: "Your last payment failed. Update your card to avoid a pause in service.",
  noSubscription: "You don't have an active subscription yet.",
  noSubscriptionTr: "You don't have an active subscription yet.",
  liveUnavailable: "We couldn't reach the payment provider right now; details will appear shortly.",
  simulated: "Test mode: the payment provider isn't configured, so details are simulated.",
  cancel: {
    button: "Cancel subscription",
    question: "When should your subscription end?",
    periodEndTitle: "At the end of the billing period (recommended)",
    periodEndBody: "Service continues until {date}, then doesn't renew. No further charges.",
    periodEndBodyNoDate: "Service continues until the end of the period you've paid for, then doesn't renew.",
    nowTitle: "Immediately",
    nowBody: "Service stops now. Remaining days are not refunded.",
    confirm: "Confirm cancellation",
    pending: "Canceling…",
    keep: "Keep subscription",
    doneNow: "Your subscription has been canceled.",
    doneAtPeriodEnd: "Your subscription is set to end at the end of the billing period.",
  },
};

export function billingCopy(market: BusinessMarket): BillingCopy {
  return market === "US" ? en : tr;
}
