CREATE TABLE reservation_settings (
 restaurant_id UUID PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, accept_reservations BOOLEAN NOT NULL DEFAULT FALSE,
 minimum_party_size INTEGER NOT NULL DEFAULT 1 CHECK(minimum_party_size > 0), maximum_party_size INTEGER NOT NULL DEFAULT 8 CHECK(maximum_party_size >= minimum_party_size),
 advance_booking_days INTEGER NOT NULL DEFAULT 30 CHECK(advance_booking_days >= 0), same_day_booking_allowed BOOLEAN NOT NULL DEFAULT TRUE,
 minimum_notice_minutes INTEGER NOT NULL DEFAULT 60 CHECK(minimum_notice_minutes >= 0), default_duration_minutes INTEGER NOT NULL DEFAULT 90 CHECK(default_duration_minutes > 0),
 buffer_minutes INTEGER NOT NULL DEFAULT 0 CHECK(buffer_minutes >= 0), reservation_interval_minutes INTEGER NOT NULL DEFAULT 30 CHECK(reservation_interval_minutes > 0), capacity_per_slot INTEGER NOT NULL DEFAULT 20 CHECK(capacity_per_slot > 0), reservation_hours JSONB NOT NULL DEFAULT '[]'
);
CREATE TABLE reservations (
 id UUID PRIMARY KEY, restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT, confirmation_code TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'CONFIRMED' CHECK(status IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED','NO_SHOW')),
 guest_name TEXT NOT NULL, guest_phone TEXT NOT NULL, guest_email TEXT, party_size INTEGER NOT NULL CHECK(party_size > 0), reservation_date DATE NOT NULL, reservation_time TIME NOT NULL,
 duration_minutes INTEGER NOT NULL CHECK(duration_minutes > 0), special_request TEXT, source TEXT NOT NULL CHECK(source IN ('AI_PHONE','ADMIN','OTHER')), originating_call_id UUID REFERENCES calls(id) ON DELETE SET NULL, conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), cancelled_at TIMESTAMPTZ, UNIQUE(restaurant_id, confirmation_code)
);
CREATE INDEX reservations_restaurant_date_idx ON reservations(restaurant_id,reservation_date,reservation_time) WHERE status IN ('PENDING','CONFIRMED');
CREATE INDEX reservations_restaurant_phone_idx ON reservations(restaurant_id,guest_phone);
CREATE TABLE reservation_events (id UUID PRIMARY KEY,reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT,event_type TEXT NOT NULL CHECK(event_type IN ('CREATED','CONFIRMED','MODIFIED','CANCELLED','MARKED_COMPLETED','MARKED_NO_SHOW')),actor_type TEXT NOT NULL CHECK(actor_type IN ('AI','STAFF','SYSTEM')),actor_id UUID,metadata JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE order_settings (restaurant_id UUID PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, accept_orders BOOLEAN NOT NULL DEFAULT FALSE, allowed_order_types JSONB NOT NULL DEFAULT '["PICKUP"]', currency TEXT NOT NULL DEFAULT 'USD', tax_basis_points INTEGER CHECK(tax_basis_points BETWEEN 0 AND 10000));
CREATE TABLE orders (id UUID PRIMARY KEY,restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT,order_number TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'CONFIRMED' CHECK(status IN ('DRAFT','CONFIRMED','CANCELLED','COMPLETED')),customer_name TEXT NOT NULL,customer_phone TEXT NOT NULL,order_type TEXT NOT NULL CHECK(order_type IN ('PICKUP','DINE_IN','OTHER')),special_instructions TEXT,subtotal_cents INTEGER NOT NULL,tax_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL,currency TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'AI_PHONE',originating_call_id UUID REFERENCES calls(id) ON DELETE SET NULL,conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),cancelled_at TIMESTAMPTZ,UNIQUE(restaurant_id,order_number));
CREATE INDEX orders_restaurant_phone_idx ON orders(restaurant_id,customer_phone);
CREATE TABLE order_items (id UUID PRIMARY KEY,order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,menu_item_id UUID NOT NULL,item_name_snapshot TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity > 0),unit_price_cents INTEGER NOT NULL,line_total_cents INTEGER NOT NULL,special_instructions TEXT);
CREATE TABLE order_item_modifiers (id UUID PRIMARY KEY,order_item_id UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,modifier_group_name_snapshot TEXT NOT NULL,modifier_option_name_snapshot TEXT NOT NULL,price_adjustment_cents INTEGER NOT NULL);
CREATE TABLE order_events (id UUID PRIMARY KEY,order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT,event_type TEXT NOT NULL CHECK(event_type IN ('CREATED','MODIFIED','CANCELLED','COMPLETED')),actor_type TEXT NOT NULL CHECK(actor_type IN ('AI','STAFF','SYSTEM')),actor_id UUID,metadata JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE action_confirmations (id UUID PRIMARY KEY,restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,conversation_id UUID,action TEXT NOT NULL,payload_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'READY' CHECK(status IN ('READY','CONFIRMED','CONSUMED','EXPIRED','CANCELLED')),expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),confirmed_at TIMESTAMPTZ,consumed_at TIMESTAMPTZ);
CREATE INDEX action_confirmations_lookup_idx ON action_confirmations(restaurant_id,conversation_id,action,status);
CREATE TABLE idempotency_records (restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,action TEXT NOT NULL,key TEXT NOT NULL,response JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(restaurant_id,action,key));
CREATE TABLE audit_events (id UUID PRIMARY KEY,restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT,actor_type TEXT NOT NULL,actor_id UUID,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id UUID NOT NULL,request_id TEXT,call_id UUID,conversation_id UUID,metadata JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
