PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS restaurants (
 id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, legal_name TEXT, description TEXT,
 phone TEXT, email TEXT, website TEXT, address TEXT, city TEXT, state TEXT, postal_code TEXT, country TEXT NOT NULL DEFAULT 'US',
 timezone TEXT NOT NULL DEFAULT 'America/New_York', default_language TEXT NOT NULL DEFAULT 'en', supported_languages TEXT NOT NULL DEFAULT '["en"]',
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('OWNER','MANAGER','STAFF')), PRIMARY KEY(user_id,restaurant_id));
CREATE TABLE IF NOT EXISTS business_hours (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, weekday INTEGER NOT NULL CHECK(weekday BETWEEN 0 AND 6), start_time TEXT NOT NULL CHECK(start_time GLOB '[0-2][0-9]:[0-5][0-9]'), end_time TEXT NOT NULL CHECK(end_time GLOB '[0-2][0-9]:[0-5][0-9]'), CHECK(start_time < end_time), UNIQUE(restaurant_id,weekday,start_time,end_time));
CREATE TABLE IF NOT EXISTS special_closures (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, date TEXT NOT NULL, start_time TEXT, end_time TEXT, reason TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, CHECK(start_time IS NULL OR end_time IS NULL OR start_time < end_time));
CREATE TABLE IF NOT EXISTS seasons (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, enabled INTEGER NOT NULL DEFAULT 0, season_start TEXT, season_end TEXT, current_status TEXT NOT NULL DEFAULT 'OPEN' CHECK(current_status IN ('OPEN','CLOSED','TEMPORARILY_CLOSED')), closed_message TEXT, reopen_message TEXT, auto_pause_billing INTEGER NOT NULL DEFAULT 0, disable_orders_when_closed INTEGER NOT NULL DEFAULT 1, disable_reservations_when_closed INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS menu_categories (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, display_order INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(restaurant_id,name));
CREATE TABLE IF NOT EXISTS menu_items (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, category_id TEXT NOT NULL REFERENCES menu_categories(id) ON DELETE RESTRICT, name TEXT NOT NULL, description TEXT, price_cents INTEGER NOT NULL CHECK(price_cents >= 0), active INTEGER NOT NULL DEFAULT 1, available INTEGER NOT NULL DEFAULT 1, unavailable_reason TEXT, display_order INTEGER NOT NULL DEFAULT 0, preparation_notes TEXT, dietary_information TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS modifier_groups (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, menu_item_id TEXT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE, name TEXT NOT NULL, required INTEGER NOT NULL DEFAULT 0, min_selections INTEGER NOT NULL DEFAULT 0 CHECK(min_selections >= 0), max_selections INTEGER NOT NULL DEFAULT 1 CHECK(max_selections >= min_selections), display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS modifier_options (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, modifier_group_id TEXT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE, name TEXT NOT NULL, price_delta_cents INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS item_allergens (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, menu_item_id TEXT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE, allergen TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('CONTAINS','MAY_CONTAIN','UNKNOWN')), UNIQUE(menu_item_id,allergen));
CREATE TABLE IF NOT EXISTS faqs (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, question TEXT NOT NULL, answer TEXT NOT NULL, category TEXT, active INTEGER NOT NULL DEFAULT 1, priority INTEGER NOT NULL DEFAULT 0, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS policies (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, type TEXT NOT NULL CHECK(type IN ('RESERVATION','CANCELLATION','LARGE_PARTY','CHILDREN','PET','TAKEOUT','DELIVERY','CORKAGE','OTHER')), title TEXT NOT NULL, description TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(restaurant_id,type,title));
CREATE TABLE IF NOT EXISTS parking (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, available INTEGER NOT NULL DEFAULT 0, type TEXT, description TEXT, cost_cents INTEGER CHECK(cost_cents IS NULL OR cost_cents >= 0), validation_required INTEGER NOT NULL DEFAULT 0, notes TEXT);
CREATE TABLE IF NOT EXISTS directions (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, directions TEXT, landmark TEXT, entrance_instructions TEXT);
CREATE TABLE IF NOT EXISTS specials (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, price_cents INTEGER CHECK(price_cents IS NULL OR price_cents >= 0), active INTEGER NOT NULL DEFAULT 1, start_date TEXT, end_date TEXT, start_time TEXT, end_time TEXT, days_of_week TEXT NOT NULL DEFAULT '[]', CHECK(start_date IS NULL OR end_date IS NULL OR start_date <= end_date));
CREATE TABLE IF NOT EXISTS ai_configurations (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, operational_instructions TEXT NOT NULL DEFAULT '', seating_note TEXT, large_party_note TEXT, allergy_note TEXT, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS human_escalation_settings (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, enabled INTEGER NOT NULL DEFAULT 0, phone TEXT, fallback_phone TEXT, transfer_message TEXT, business_hours_only INTEGER NOT NULL DEFAULT 0, after_hours_behavior TEXT NOT NULL DEFAULT 'VOICEMAIL', escalation_categories TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS reservation_settings (restaurant_id TEXT PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE, reservations_enabled INTEGER NOT NULL DEFAULT 0, minimum_party_size INTEGER NOT NULL DEFAULT 1 CHECK(minimum_party_size > 0), maximum_party_size INTEGER NOT NULL DEFAULT 8 CHECK(maximum_party_size >= minimum_party_size), advance_booking_days INTEGER NOT NULL DEFAULT 30 CHECK(advance_booking_days >= 0), minimum_notice_minutes INTEGER NOT NULL DEFAULT 60 CHECK(minimum_notice_minutes >= 0), default_duration_minutes INTEGER NOT NULL DEFAULT 90 CHECK(default_duration_minutes > 0), reservation_hours TEXT NOT NULL DEFAULT '[]', large_party_threshold INTEGER NOT NULL DEFAULT 8, large_party_requires_human INTEGER NOT NULL DEFAULT 1, cancellation_policy TEXT, notes TEXT);
CREATE INDEX IF NOT EXISTS idx_menu_items_tenant ON menu_items(restaurant_id, category_id);
CREATE INDEX IF NOT EXISTS idx_faq_tenant ON faqs(restaurant_id);
