import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Db } from '../db/database.js';
import { id, json, now } from '../db/database.js';
import { RestaurantContextService } from '../services/restaurant-context.service.js';

type Resource={table:string;columns:string[]};
const resources:Record<string,Resource>={hours:{table:'business_hours',columns:['weekday','start_time','end_time']},closures:{table:'special_closures',columns:['date','start_time','end_time','reason','active']},categories:{table:'menu_categories',columns:['name','description','display_order','active']},items:{table:'menu_items',columns:['category_id','name','description','price_cents','active','available','unavailable_reason','display_order','preparation_notes','dietary_information']},modifierGroups:{table:'modifier_groups',columns:['menu_item_id','name','required','min_selections','max_selections','display_order']},modifierOptions:{table:'modifier_options',columns:['modifier_group_id','name','price_delta_cents','active','display_order']},allergens:{table:'item_allergens',columns:['menu_item_id','allergen','status']},faqs:{table:'faqs',columns:['question','answer','category','active','priority','display_order']},policies:{table:'policies',columns:['type','title','description','active']},specials:{table:'specials',columns:['name','description','price_cents','active','start_date','end_date','start_time','end_time','days_of_week']}};
const profile=['slug','name','legal_name','description','phone','email','website','address','city','state','postal_code','country','timezone','default_language','supported_languages','status'];
const setting:Record<string,{table:string;fields:string[]} >={season:{table:'seasons',fields:['enabled','season_start','season_end','current_status','closed_message','reopen_message','auto_pause_billing','disable_orders_when_closed','disable_reservations_when_closed']},parking:{table:'parking',fields:['available','type','description','cost_cents','validation_required','notes']},directions:{table:'directions',fields:['directions','landmark','entrance_instructions']},ai:{table:'ai_configurations',fields:['operational_instructions','seating_note','large_party_note','allergy_note']},escalation:{table:'human_escalation_settings',fields:['enabled','phone','fallback_phone','transfer_message','business_hours_only','after_hours_behavior','escalation_categories']},reservations:{table:'reservation_settings',fields:['reservations_enabled','minimum_party_size','maximum_party_size','advance_booking_days','minimum_notice_minutes','default_duration_minutes','reservation_hours','large_party_threshold','large_party_requires_human','cancellation_policy','notes']}};
function tenant(db:Db,req:FastifyRequest){const uid=req.headers['x-user-id'],rid=req.headers['x-restaurant-id'];if(typeof uid!=='string'||typeof rid!=='string')throw Object.assign(new Error('Authentication and restaurant context are required'),{statusCode:401});if(!db.prepare('SELECT 1 FROM memberships WHERE user_id=? AND restaurant_id=?').get(uid,rid))throw Object.assign(new Error('Forbidden restaurant context'),{statusCode:403});return rid;}
function body(input:unknown,fields:string[]){const value=z.record(z.unknown()).parse(input);return Object.fromEntries(fields.filter(k=>k in value).map(k=>[k,typeof value[k]==='object'&&value[k]!==null?json(value[k]):value[k]]));}
export async function registerApi(app:FastifyInstance,db:Db){const context=new RestaurantContextService(db);app.get('/health',async()=>({status:'ok'}));app.get('/api/docs',async()=>({authentication:'x-user-id and x-restaurant-id headers; membership verified server-side',resources:Object.keys(resources),settings:Object.keys(setting)}));app.get('/api/context',async req=>context.get(tenant(db,req)));app.get('/api/restaurant',async req=>db.prepare('SELECT * FROM restaurants WHERE id=?').get(tenant(db,req)));app.patch('/api/restaurant',async req=>{const rid=tenant(db,req),d=body(req.body,profile);if(!Object.keys(d).length)throw Object.assign(new Error('No valid fields'),{statusCode:400});const set=Object.keys(d).map(k=>`${k}=?`).join(',');db.prepare(`UPDATE restaurants SET ${set},updated_at=? WHERE id=?`).run(...Object.values(d),now(),rid);return db.prepare('SELECT * FROM restaurants WHERE id=?').get(rid);});
 app.get('/api/:resource',async req=>{const rid=tenant(db,req),r=resources[(req.params as any).resource];if(!r)throw Object.assign(new Error('Unknown resource'),{statusCode:404});return db.prepare(`SELECT * FROM ${r.table} WHERE restaurant_id=? ORDER BY id`).all(rid);});
 app.post('/api/:resource',async req=>{const rid=tenant(db,req),r=resources[(req.params as any).resource];if(!r)throw Object.assign(new Error('Unknown resource'),{statusCode:404});const d=body(req.body,r.columns);if(!Object.keys(d).length)throw Object.assign(new Error('No valid fields'),{statusCode:400});for(const [field,table] of [['category_id','menu_categories'],['menu_item_id','menu_items'],['modifier_group_id','modifier_groups']] as const)if(field in d&&!db.prepare(`SELECT id FROM ${table} WHERE id=? AND restaurant_id=?`).get(d[field],rid))throw Object.assign(new Error(`${field} does not belong to restaurant`),{statusCode:400});const values:any={id:id(),restaurant_id:rid,...d};if(['menu_categories','menu_items'].includes(r.table)){values.created_at=now();values.updated_at=now();}db.prepare(`INSERT INTO ${r.table} (${Object.keys(values).join(',')}) VALUES (${Object.keys(values).map(()=>'?').join(',')})`).run(...Object.values(values));return values;});
 app.get('/api/settings/:setting',async req=>{const rid=tenant(db,req),s=setting[(req.params as any).setting];if(!s)throw Object.assign(new Error('Unknown setting'),{statusCode:404});return db.prepare(`SELECT * FROM ${s.table} WHERE restaurant_id=?`).get(rid)??{state:'NOT_CONFIGURED'};});app.put('/api/settings/:setting',async req=>{const rid=tenant(db,req),s=setting[(req.params as any).setting];if(!s)throw Object.assign(new Error('Unknown setting'),{statusCode:404});const d=body(req.body,s.fields),keys=['restaurant_id',...Object.keys(d)],values=[rid,...Object.values(d)];db.prepare(`INSERT INTO ${s.table} (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')}) ON CONFLICT(restaurant_id) DO UPDATE SET ${Object.keys(d).map(k=>`${k}=excluded.${k}`).join(',')}`).run(...values);return db.prepare(`SELECT * FROM ${s.table} WHERE restaurant_id=?`).get(rid);});}
